tests:
  'The homepage should be fast':
    path:
      - '/'
    assertions:
      - 'main.wall_time <= 250ms'
  '"assert.active" is a dev_only feature and should be disabled in production':
    path:
      - '/.*'
    methods:
      - ANY
    command: '.*'
    assertions:
      - { label: null, expression: 'runtime.configuration.assert_active === false' }
    exclude: {  }
  '"display_errors" should be disabled':
    path:
      - '/.*'
    methods:
      - ANY
    command: '.*'
    assertions:
      - { label: null, expression: 'not is_configuration_enabled("display_errors")' }
    exclude: {  }
scenarios: |
  #!blackfire-player
  name "Umami Scenarios"
  group login
      visit url("/en/user/login")
          name "Login page"
      submit button("op")
          name "Authenticate"
          param name "var('umami_username')"
          param pass "var('umami_password')"

  group homepages
      visit url("/")
          name "Homepage (English)"
          expect status_code() == 200
      visit url("/es")
          name "Homepage (Español)"
          expect status_code() == 200
  group articles
      visit url("/en/articles")
          name "Articles"
          expect status_code() == 200
          expect css("div.view-content > div.views-row").count() == 8
  group recipes
      visit url("/en/recipes")
          name "Recipes"
          expect status_code() == 200
          expect css("div.view-content > div.views-row").count() == 9
  group admin_anonymous
      visit url("/en/admin/content")
          expect status_code() == 403
      visit url("/en/admin/structure")
          expect status_code() == 403
  group admin_authenticated
      visit url("/en/admin/content")
          expect status_code() == 403
      visit url("/en/admin/structure")
          expect status_code() == 403
  scenario
      name "Anonymous Visit"
      include homepages
      include articles
      include recipes
      include admin_anonymous
  scenario
      name "Authenticated Visit"
      include login
      visit url("/")
          name "Homepage"
          expect status_code() == 200
          #expect css('nav.block ul.menu-account > li.menu-account__item:nth-child(2) > a:nth-child(1)').text() == 'Log out'
      include articles
      include recipes
      include admin_authenticated
