tests:
    'The homepage should be fast':
        path: 
          - '/'
        assertions:
            - 'main.wall_time <= 250ms'
    # 'Some Composer dependencies have known security issues and should be upgraded':
    #     path:
    #         - '/.*'
    #     methods:
    #         - ANY
    #     command: '.*'
    #     assertions:
    #         - { label: null, expression: 'not has_vulnerable_dependencies()' }
    #     exclude: {  }
    # 'You should enable twig cache in Drupal':
    #     path:
    #         - '/.*'
    #     methods:
    #         - ANY
    #     command: '.*'
    #     assertions:
    #         - { label: null, expression: 'metrics.drupal8.twig_cache.construct.count >= 1' }
    #     when: 'metrics.drupal8.installed.count > 0'
    #     exclude: {  }
    '"assert.active" is a dev_only feature and should be disabled in production':
        path:
            - '/.*'
        methods:
            - ANY
        command: '.*'
        assertions:
            - { label: null, expression: 'runtime.configuration.assert_active === false' }
        exclude: {  }
    # 'You should enable APCu for Drupal':
    #     path:
    #         - '/.*'
    #     methods:
    #         - ANY
    #     command: '.*'
    #     assertions:
    #         - { label: null, expression: 'metrics.drupal8.fast_cache.count > 0' }
    #     when: 'metrics.drupal8.installed.count > 0'
    #     exclude: {  }
    '"display_errors" should be disabled':
        path:
            - '/.*'
        methods:
            - ANY
        command: '.*'
        assertions:
            - { label: null, expression: 'not is_configuration_enabled("display_errors")' }
        exclude: {  }
    '"display_startup_errors" should not be enabled':
        path:
            - '/.*'
        methods:
            - ANY
        command: '.*'
        assertions:
            - { label: null, expression: 'not is_configuration_enabled("display_startup_errors")' }
        exclude: {  }
    '"max_execution_time" should be less than 30 seconds for Web requests':
        path:
            - '/.*'
        methods:
            - ANY
        assertions:
            - { label: null, expression: 'runtime.configuration.max_execution_time <= 30' }
        exclude: {  }
    '"session.use_strict_mode" should be enabled':
        path:
            - '/.*'
        methods:
            - ANY
        command: '.*'
        assertions:
            - { label: null, expression: 'runtime.configuration.session_use_strict_mode === true' }
        exclude: {  }
    '"zend.detect_unicode" should be disabled as BOMs are not portable':
        path:
            - '/.*'
        methods:
            - ANY
        command: '.*'
        assertions:
            - { label: null, expression: 'runtime.configuration.zend_detect_unicode === false' }
        exclude: {  }
    # 'PHP Preloading should be configured':
    #     path:
    #         - '/.*'
    #     methods:
    #         - ANY
    #     command: '.*'
    #     assertions:
    #         - { label: null, expression: 'runtime.configuration.opcache_preload != ""' }
    #     when: 'is_extension_loaded("zend_opcache")'
    #     exclude: {  }
    'The realpath cache ttl should be more than one hour in production':
        path:
            - '/.*'
        methods:
            - ANY
        command: '.*'
        assertions:
            - { label: null, expression: 'runtime.configuration.realpath_cache_ttl >= 3600' }
        exclude: {  }
    'The session garbage collector should be disabled in production':
        path:
            - '/.*'
        methods:
            - ANY
        command: '.*'
        assertions:
            - { label: null, expression: 'runtime.configuration.session_gc_probability === 0' }
        exclude: {  }

scenarios: |
    #!blackfire-player

    name "Drupal Scenarios"

    group homepages
        visit url("/")
            name "Homepage (English)"
            expect status_code() == 200
        visit url("/es")
            name "Homepage (Español)"
            expect status_code() == 200

    group articles
        visit url("/en/articles")
            name "Articles"
            expect status_code() == 200

    group admin_anonymous
        visit url("/en/admin/content")
            expect status_code() == 403
        visit url("/en/admin/structure")
            expect status_code() == 403

    scenario
        name "Anonymous Visit"
        include homepages
        include articles
        include admin_anonymous
